const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Compliance = require('./models/Compliance');

dotenv.config();

const compliances = [
  { complianceId: 'REC-01', type: 'recurring', act: 'CMR 2017', title: 'DGMS periodical production & employment return', detail: 'Periodical statistical return of output & persons employed.', dept: 'Stats / Mgr', recurrence: 'Monthly', dueDate: '10th of each month', alertDate: '5th of each month', authority: 'DGMS Regional Office, Bilaspur', penalty: '₹50k–₹1 lakh' },
  { complianceId: 'REC-02', type: 'recurring', act: 'CM(SP) Act 2015', title: 'Monthly production/dispatch report to Nominated Authority', detail: 'Drives monthly payment/levy.', dept: 'Commercial', recurrence: 'Monthly', dueDate: 'Per CMDPA cadence', alertDate: '', authority: 'Nominated Authority, Ministry of Coal', penalty: 'Appropriation of Performance Security' },
  { complianceId: 'REC-03', type: 'recurring', act: 'CMCD Act 1974', title: 'Returns to Coal Controller', detail: 'Conservation & grade reporting.', dept: 'Commercial/Quality', recurrence: 'Monthly', dueDate: 'Per CCO cadence', alertDate: '', authority: 'Coal Controller Organisation, Kolkata', penalty: 'CMCD Act penalties' },
  { complianceId: 'REC-04', type: 'recurring', act: 'Explosives Rules 2008', title: 'Explosives magazine monthly return', detail: 'Magazine stock/consumption return.', dept: 'Magazine i/c', recurrence: 'Monthly', dueDate: 'By 10th of succeeding month', alertDate: '5th of succeeding month', authority: 'District Magistrate, Raigarh', penalty: 'Licence suspension' },
  { complianceId: 'REC-05', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Respirable-dust sampling', detail: 'Sample air once/month; record within 14 days.', dept: 'Environment/Safety', recurrence: 'Monthly', dueDate: 'Once every month', alertDate: '', authority: 'DGMS', penalty: 'OSH Code s.96/s.99' },
  { complianceId: 'REC-06', type: 'recurring', act: 'EC / EP Act 1986', title: 'Monthly environment monitoring report', detail: 'Air/water/noise monitoring report.', dept: 'Environment', recurrence: 'Monthly', dueDate: 'By 5th of every month', alertDate: '1st of every month', authority: 'CECB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-07', type: 'recurring', act: 'EC (EP Act 1986)', title: 'ROM/coal ash-content record + website upload', detail: 'Per EC cond.19 & 25.', dept: 'Quality/CHP', recurrence: 'Monthly', dueDate: 'Monthly upload', alertDate: '', authority: 'MoEFCC RO Bhopal', penalty: 'EP Act penalties' },
  { complianceId: 'REC-08', type: 'recurring', act: 'EC / CPCB', title: 'CAAQMS continuous data transmission', detail: 'Continuous transmission to CECB/CPCB server.', dept: 'Environment', recurrence: 'Continuous', dueDate: 'Continuous', alertDate: '', authority: 'CECB / CPCB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-09', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Manpower distribution plan / monthly survey', detail: 'Survey of persons employed in first week of every month.', dept: 'Mgr / Time office', recurrence: 'Monthly', dueDate: 'First week of every month', alertDate: '', authority: 'DGMS', penalty: 'OSH Code s.96' },
  { complianceId: 'REC-10', type: 'recurring', act: 'Code on Social Security 2020', title: 'PF / Pension / ESI monthly contributions & returns', detail: 'Ex-CMPF/EPF/ESI contributions.', dept: 'Accounts/HR', recurrence: 'Monthly', dueDate: 'Statutory monthly dates', alertDate: '', authority: 'CMPFO/EPFO; ESIC', penalty: 'SS-Code penalties' },
  { complianceId: 'REC-11', type: 'recurring', act: 'EC / EP Act 1986', title: 'Groundwater / piezometer monitoring', detail: 'Pre/monsoon/post/winter cycle.', dept: 'Environment', recurrence: 'Quarterly', dueDate: 'Aug 2026; Nov 2026', alertDate: 'Jul 2026; Oct 2026', authority: 'MoEFCC RO Bhopal', penalty: 'EP Act; NOC cancellation' },
  { complianceId: 'REC-12', type: 'recurring', act: 'EC conditions', title: 'Quarterly environmental monitoring — IIT-KGP/CIMFR', detail: 'Third-party quarterly monitoring.', dept: 'Environment', recurrence: 'Quarterly', dueDate: '30-Sep-2026', alertDate: '15-Sep-2026', authority: 'MoEFCC RO Bhopal', penalty: 'EP Act penalties' },
  { complianceId: 'REC-13', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Safety Management Plan (SMP) quarterly review', detail: 'Review risk-control effectiveness.', dept: 'Safety', recurrence: 'Quarterly', dueDate: '30-Sep-2026', alertDate: '15-Sep-2026', authority: 'Regional I-c-F', penalty: '₹2–3 lakh' },
  { complianceId: 'REC-14', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Statutory plans & sections update', detail: 'Keep current to scale.', dept: 'Surveyor', recurrence: 'Quarterly', dueDate: '30-Sep-2026', alertDate: '15-Sep-2026', authority: 'DGMS', penalty: 'OSH Code s.98' },
  { complianceId: 'REC-15', type: 'recurring', act: 'Mines Vocational Training Rules 1966', title: 'Vocational & refresher training', detail: 'Per training calendar including HEMM operators.', dept: 'Training Officer', recurrence: 'Quarterly', dueDate: 'Per training calendar', alertDate: '', authority: 'DGMS-approved VT Centre', penalty: 'OSH Code s.97' },
  { complianceId: 'REC-16', type: 'recurring', act: 'EP Act 1986', title: 'EC six-monthly compliance report', detail: 'Apr–Sep period report.', dept: 'Environment', recurrence: 'Half-yearly', dueDate: '01-Dec-2026', alertDate: '01-Nov-2026', authority: 'MoEFCC RO, Bhopal', penalty: 'EP Act penalties' },
  { complianceId: 'REC-17', type: 'recurring', act: 'EIA 2006', title: 'EC compliance status web-upload', detail: 'At least once in six months.', dept: 'Environment/IT', recurrence: 'Half-yearly', dueDate: '31-Dec-2026', alertDate: '01-Dec-2026', authority: 'Company website / MoEFCC', penalty: 'EP Act penalties' },
  { complianceId: 'REC-18', type: 'recurring', act: 'OSH Rules 2026', title: 'Annual Return of the establishment', detail: 'For CY 2026; portal return FORM-XVIII.', dept: 'Mgr / HR', recurrence: 'Annual', dueDate: '28-Feb-2027', alertDate: '31-Jan-2027', authority: 'Inspector-cum-Facilitator', penalty: '₹50k–₹2 lakh' },
  { complianceId: 'REC-19', type: 'recurring', act: 'CMR 2017', title: 'DGMS Annual Return of the mine', detail: 'For CY 2026.', dept: 'Mgr / Stats', recurrence: 'Annual', dueDate: '21-Jan-2027', alertDate: '31-Dec-2026', authority: 'DGMS', penalty: 'OSH Code s.96/s.99' },
  { complianceId: 'REC-20', type: 'recurring', act: 'OSH Rules 2026', title: 'Annual medical examination (PME)', detail: 'Before employment & every year.', dept: 'Medical Officer', recurrence: 'Annual', dueDate: 'Per anniversary', alertDate: '30 days prior', authority: 'Mine Medical Officer', penalty: 'OSH Code s.94/s.97' },
  { complianceId: 'REC-21', type: 'recurring', act: 'EC cond.34', title: 'Occupational-health surveillance', detail: 'Conducted at Fortis Hospital.', dept: 'Medical Officer', recurrence: 'Annual', dueDate: 'Annual', alertDate: '30 days prior', authority: 'MoEFCC & DGMS', penalty: 'EP Act + OSH Code' },
  { complianceId: 'REC-22', type: 'recurring', act: 'EP Rules 1986', title: 'Environment Statement (Form-V)', detail: 'FY ending 31.03.2026.', dept: 'Environment', recurrence: 'Annual', dueDate: '30-Sep-2026', alertDate: '31-Aug-2026', authority: 'CECB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-23', type: 'recurring', act: 'Hazardous Waste Rules 2016', title: 'Hazardous Waste — annual return', detail: 'HWA No.658/HO/HSMD/CECB.', dept: 'Environment', recurrence: 'Annual', dueDate: '30-Jun-2026', alertDate: '15-Jun-2026', authority: 'CECB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-24', type: 'recurring', act: 'Battery Waste Rules 2022', title: 'Battery Waste — annual return', detail: 'HEMM/vehicle batteries.', dept: 'Environment', recurrence: 'Annual', dueDate: '15-Jun-2026', alertDate: '05-Jun-2026', authority: 'CPCB / CECB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-25', type: 'recurring', act: 'E-Waste Rules 2022', title: 'E-Waste — annual return', detail: 'Office/electrical e-waste.', dept: 'Environment', recurrence: 'Annual', dueDate: '15-Jun-2026', alertDate: '05-Jun-2026', authority: 'CPCB / CECB', penalty: 'EP Act penalties' },
  { complianceId: 'REC-26', type: 'recurring', act: 'Public Liability Insurance Act 1991', title: 'Public Liability Insurance — renewal', detail: 'Policy No. 41105056 expires 30.06.2026.', dept: 'Insurance/Admin', recurrence: 'Annual', dueDate: '30-Jun-2026', alertDate: '15-Jun-2026', authority: 'Insurer', penalty: 'PLIA penalties' },
  { complianceId: 'REC-27', type: 'recurring', act: 'Air Act 1981 / Water Act 1974', title: 'Consent to Operate (CTO) — renewal', detail: 'Current CTO valid 31.12.2026.', dept: 'Environment', recurrence: 'Annual', dueDate: 'Apply by Q4 2026', alertDate: '01-Oct-2026', authority: 'CECB', penalty: 'Closure direction' },
  { complianceId: 'REC-28', type: 'recurring', act: 'EP Act 1986 (CGWA)', title: 'CGWA NOC — renewal + annual water return', detail: 'NOC valid 28.09.2026.', dept: 'Environment', recurrence: 'Annual', dueDate: '28-Sep-2026', alertDate: '29-Aug-2026', authority: 'Central Ground Water Authority', penalty: 'NOC cancellation' },
  { complianceId: 'REC-29', type: 'recurring', act: 'Explosives Rules 2008', title: 'Magazine lightning-conductor earth-resistance test', detail: 'Test earth resistance once/year.', dept: 'Electrical/Magazine', recurrence: 'Annual', dueDate: 'Once a year', alertDate: '30 days prior', authority: 'PESO', penalty: 'Licence action' },
  { complianceId: 'REC-30', type: 'recurring', act: 'Electricity Act 2003', title: 'Electrical installations — periodic testing & certification', detail: 'Per CEA cycle.', dept: 'Electrical Supvr', recurrence: 'Annual', dueDate: 'Per CEA periodic cycle', alertDate: '30 days prior', authority: 'State Electrical Inspectorate', penalty: 'Electricity Act penalties' },
  { complianceId: 'REC-31', type: 'recurring', act: 'Energy Conservation Act 2001', title: 'Energy Audit — designated-consumer cycle', detail: 'Done 10.09.2025, valid 3 yrs.', dept: 'Energy mgr', recurrence: 'Triennial', dueDate: 'Sep-2028', alertDate: 'Jun-2028', authority: 'BEE', penalty: 'EC Act penalties' },
  { complianceId: 'REC-32', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Slope-stability scientific study', detail: 'Review on major change in method/geo-mining.', dept: 'Mining/Geotech', recurrence: 'Annual', dueDate: 'Annual / on major change', alertDate: '30 days prior', authority: 'DGMS', penalty: 'OSH Code s.94' },
  { complianceId: 'REC-33', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Emergency response & evacuation plan — drills', detail: 'Periodic mock drills; ERP annual review.', dept: 'Safety', recurrence: 'Annual', dueDate: 'Annual review', alertDate: '30 days prior', authority: 'Regional Inspector-cum-Facilitator', penalty: 'OSH Code s.94' },
  { complianceId: 'REC-34', type: 'recurring', act: 'Draft OSH Regs 2026', title: 'Whole-body vibration assessment (HEMM operators)', detail: 'ELV/EAV assessment.', dept: 'Safety/Medical', recurrence: 'Annual', dueDate: 'Annual', alertDate: '30 days prior', authority: 'DGMS', penalty: 'OSH Code s.94' },
  { complianceId: 'REC-35', type: 'recurring', act: 'EC / Draft OSH Regs 2026', title: 'Noise survey & control verification', detail: 'Periodic survey of zones ≥85 dBA.', dept: 'Safety/Environment', recurrence: 'Annual', dueDate: 'Annual / periodic', alertDate: '30 days prior', authority: 'CECB/DGMS', penalty: 'EP Act + OSH Code' },
  { complianceId: 'REC-36', type: 'recurring', act: 'EC cond.35', title: 'Land-use time-series mapping', detail: 'Once in 3 years per EC.', dept: 'Environment/GIS', recurrence: 'Triennial', dueDate: 'Per 3-yr cycle', alertDate: '', authority: 'MoEFCC RO Bhopal', penalty: 'EP Act penalties' },
  { complianceId: 'REC-37', type: 'recurring', act: 'Fly Ash Notification 2021', title: 'Fly-ash utilisation — annual return', detail: '25:75 fly-ash:OB; DGMS-approved filling.', dept: 'Environment/Mining', recurrence: 'Annual', dueDate: 'Annual cycle 2026', alertDate: '30 days prior', authority: 'MoEFCC / CEA / CECB', penalty: 'EP Act + OSH Code' },
  { complianceId: 'REC-38', type: 'recurring', act: 'OSH Rules 2026', title: 'Contractor licence(s) renewal', detail: 'MDOs PC Patel, Dashmesh. Licence valid 5 yrs.', dept: 'Contracts/HR', recurrence: 'Multi-year', dueDate: '30–90 days before expiry', alertDate: '90 days before expiry', authority: 'Shram Suvidha', penalty: '+25% late fee' },
  { complianceId: 'REC-39', type: 'recurring', act: 'Explosives Rules 2008', title: 'Explosives possession-&-use licence (LE-3) renewal', detail: 'E/CB/CG/22/22 expires 31.03.2030.', dept: 'Magazine/Safety', recurrence: 'Multi-year', dueDate: '31-Mar-2030', alertDate: '31-Dec-2029', authority: 'PESO, Bhopal', penalty: 'Licence lapse' },
  { complianceId: 'EVT-01', type: 'event', act: 'Draft OSH Regs 2026', title: 'Notice of appointment/cessation of statutory officials', detail: 'Manager, Asst Mgr, Engineer, Surveyor changes.', dept: 'Mgr / HR', recurrence: 'Event-based', dueDate: 'Within 7 days of event', alertDate: 'On trigger', authority: 'DGMS', penalty: '₹1 lakh' },
  { complianceId: 'EVT-02', type: 'event', act: 'Draft OSH Regs 2026', title: 'Manager handover — charge report', detail: 'Outgoing to incoming Manager.', dept: 'Mgr', recurrence: 'Event-based', dueDate: 'On the change', alertDate: 'On trigger', authority: 'Regional Inspector-cum-Facilitator', penalty: 'OSH Code s.96' },
  { complianceId: 'EVT-03', type: 'event', act: 'Draft OSH Regs 2026', title: 'Appointment of Agent / authorised persons', detail: 'Statement of names/designations/responsibilities.', dept: 'Owner/Occupier', recurrence: 'Event-based', dueDate: 'Within 7 days', alertDate: 'On trigger', authority: 'Chief I-c-F + Regional I-c-F', penalty: 'OSH Code s.96' },
  { complianceId: 'EVT-04', type: 'event', act: 'Draft OSH Regs 2026', title: 'Authorise acting Manager (Manager absent)', detail: 'Certificated person to act, max 60 days.', dept: 'Owner/Agent', recurrence: 'Event-based', dueDate: 'Forthwith', alertDate: 'On trigger', authority: 'Regional I-c-F', penalty: 'OSH Code s.105' },
  { complianceId: 'EVT-05', type: 'event', act: 'CEA Regs 2023', title: 'Appointment/change of Electrical Supervisor', detail: 'CEA-licensed competent person.', dept: 'Electrical/HR', recurrence: 'Event-based', dueDate: 'Before taking charge', alertDate: 'On trigger', authority: 'State Electrical Inspectorate', penalty: 'Electricity Act penalties' },
  { complianceId: 'EVT-06', type: 'event', act: 'Draft OSH Regs 2026', title: 'Appointment/change of Blasting in-charge', detail: 'Valid competency/permit; update records.', dept: 'Safety/Magazine', recurrence: 'Event-based', dueDate: 'Before assuming charge', alertDate: 'On trigger', authority: 'DGMS; PESO', penalty: 'OSH Code + Explosives Act' },
  { complianceId: 'EVT-07', type: 'event', act: 'OSH Code', title: 'Establishment registration particulars change', detail: 'Change in ownership/management.', dept: 'HR/Admin', recurrence: 'Event-based', dueDate: 'Within 30 days', alertDate: 'On trigger', authority: 'Shram Suvidha', penalty: '₹2–3 lakh' },
  { complianceId: 'EVT-08', type: 'event', act: 'OSH Code', title: 'Establishment registration (new/applicability)', detail: 'Apply for registration.', dept: 'HR/Admin', recurrence: 'Event-based', dueDate: 'Within 60 days', alertDate: 'On trigger', authority: 'Shram Suvidha', penalty: 'OSH Code s.94' },
  { complianceId: 'EVT-09', type: 'event', act: 'OSH Code', title: 'Notice of commencement/cessation of operation', detail: 'Electronic notice.', dept: 'Mgr', recurrence: 'Event-based', dueDate: '30 days before opening', alertDate: 'On trigger', authority: 'DGMS', penalty: 'OSH Code s.94/s.97' },
  { complianceId: 'EVT-10', type: 'event', act: 'OSH Code', title: 'Contractor licence (≥50 contract labour)', detail: 'MDO licence + principal-employer compliance.', dept: 'Contracts/HR', recurrence: 'Event-based', dueDate: 'Before engaging', alertDate: 'On trigger', authority: 'Shram Suvidha', penalty: 'OSH Code s.97' },
  { complianceId: 'EVT-11', type: 'event', act: 'OSH Code', title: 'Contractor work-order intimation', detail: 'Contractor intimates work order.', dept: 'Contracts', recurrence: 'Event-based', dueDate: 'Within 15 days', alertDate: 'On trigger', authority: 'Shram Suvidha', penalty: 'Licence suspension' },
  { complianceId: 'EVT-12', type: 'event', act: 'OSH Code', title: 'Closure of establishment intimation', detail: 'Inform closing + certify dues paid.', dept: 'HR/Mgr', recurrence: 'Event-based', dueDate: 'Within 30 days', alertDate: 'On trigger', authority: 'Shram Suvidha', penalty: 'OSH Code s.94' },
  { complianceId: 'EVT-13', type: 'event', act: 'OSH Code', title: 'Notice of accident (death OR injury ≥48 hrs)', detail: 'Notice + preserve & sketch site.', dept: 'Mgr/Safety', recurrence: 'Event-based', dueDate: 'Forthwith + within 7 days', alertDate: 'On trigger', authority: 'DGMS; District Magistrate', penalty: '≥₹5 lakh' },
  { complianceId: 'EVT-14', type: 'event', act: 'OSH Code', title: 'Notice of dangerous occurrence', detail: 'Bench/dump failure, HEMM overturn, fire etc.', dept: 'Mgr/Safety', recurrence: 'Event-based', dueDate: 'Forthwith', alertDate: 'On trigger', authority: 'DGMS', penalty: '₹2–3 lakh' },
  { complianceId: 'EVT-15', type: 'event', act: 'OSH Code', title: 'Notice of notifiable disease', detail: 'Coal-miners pneumoconiosis, silicosis, NIHL etc.', dept: 'Medical Officer', recurrence: 'Event-based', dueDate: 'On detection', alertDate: 'On trigger', authority: 'Chief Inspector-cum-Facilitator', penalty: '₹10,000' },
  { complianceId: 'EVT-16', type: 'event', act: 'Draft OSH Regs 2026', title: 'Preserve & sketch place of fatal/serious accident', detail: 'Duplicate signed sketch + photos.', dept: 'Mgr/Surveyor/Safety', recurrence: 'Event-based', dueDate: 'Before site disturbed', alertDate: 'On trigger', authority: 'Inspector-cum-Facilitator', penalty: 'OSH Code s.94' },
  { complianceId: 'EVT-17', type: 'event', act: 'Draft OSH Regs 2026', title: 'Scheme of mining for new pit', detail: 'Scientific-study-based scheme.', dept: 'Mining/Planning', recurrence: 'Event-based', dueDate: '60 days before starting work', alertDate: '60 days before', authority: 'DGMS', penalty: 'OSH Code s.94/s.97' },
  { complianceId: 'EVT-18', type: 'event', act: 'Draft OSH Regs 2026', title: 'Notice of abandonment/closure/discontinuance', detail: 'Reasons + persons affected; file returns.', dept: 'Mgr', recurrence: 'Event-based', dueDate: '30 days before', alertDate: '30 days before', authority: 'DGMS; District Magistrate', penalty: 'OSH Code s.96/s.99' },
  { complianceId: 'EVT-19', type: 'event', act: 'Draft OSH Regs 2026', title: 'Notice of re-opening (after >60-day stoppage)', detail: 'Notice + communicate actual reopening date.', dept: 'Mgr', recurrence: 'Event-based', dueDate: '30 days before resumption', alertDate: '30 days before', authority: 'DGMS; District Magistrate', penalty: 'OSH Code s.96' },
  { complianceId: 'EVT-20', type: 'event', act: 'Draft OSH Regs 2026', title: 'Commissioning of new HEMM / plant / machinery', detail: 'Immediate dust measurement; machinery exam logbook.', dept: 'Engineer/Safety', recurrence: 'Event-based', dueDate: 'Immediately upon commissioning', alertDate: 'On trigger', authority: 'DGMS', penalty: 'OSH Code s.96/s.94' },
  { complianceId: 'EVT-21', type: 'event', act: 'Electricity Act 2003', title: 'Commissioning/modification of HT installation', detail: 'CEA approval & testing before energising.', dept: 'Electrical Engineer', recurrence: 'Event-based', dueDate: 'Before energising', alertDate: 'On trigger', authority: 'State Electrical Inspectorate', penalty: 'Electricity Act penalties' },
  { complianceId: 'EVT-22', type: 'event', act: 'Explosives Rules 2008', title: 'New/modified magazine or change in explosive storage', detail: 'Amend/fresh PESO licence; DGMS site approval.', dept: 'Magazine/Safety', recurrence: 'Event-based', dueDate: 'Before storage/use begins', alertDate: 'On trigger', authority: 'PESO; DGMS', penalty: 'Licence action' },
  { complianceId: 'EVT-23', type: 'event', act: 'Draft OSH Regs 2026', title: 'Use of ANFO/SMS/emulsion in OC blasting', detail: 'Only under Chief I-c-F conditions.', dept: 'Blasting/Mining', recurrence: 'Event-based', dueDate: 'Before adopting practice', alertDate: 'On trigger', authority: 'DGMS', penalty: 'OSH Code s.94/s.97' },
  { complianceId: 'EVT-24', type: 'event', act: 'Ammonium Nitrate Rules 2012', title: 'Storage of ammonium nitrate as oxidiser', detail: 'Licence / AN storage compliance.', dept: 'Magazine i/c', recurrence: 'Event-based', dueDate: 'Before storage begins', alertDate: 'On trigger', authority: 'PESO / District Authority', penalty: 'Explosives Act penalties' },
  { complianceId: 'EVT-25', type: 'event', act: 'Petroleum Act 1934', title: 'New/increased bulk HSD (diesel) storage', detail: 'Obtain/amend petroleum storage licence.', dept: 'Stores/Safety', recurrence: 'Event-based', dueDate: 'Before storage', alertDate: 'On trigger', authority: 'PESO', penalty: 'Petroleum Act penalties' },
  { complianceId: 'EVT-26', type: 'event', act: 'EP Act 1986 / EIA 2006', title: 'Capacity increase beyond EC cap 6.25 MTPA', detail: 'Fresh/amended EC, CTE, CTO before exceeding capacity.', dept: 'Environment/Planning', recurrence: 'Event-based', dueDate: 'Before exceeding sanctioned capacity', alertDate: 'Ahead of ramp', authority: 'MoEFCC; CECB', penalty: 'EC revocation' },
  { complianceId: 'EVT-27', type: 'event', act: 'EIA 2006', title: 'EC grant/amendment — public notice & display', detail: 'Newspaper ad; site & office display; web upload.', dept: 'Environment/Legal', recurrence: 'Event-based', dueDate: 'Within 7 days; display 30 days', alertDate: 'On trigger', authority: 'MoEFCC', penalty: 'EP Act penalties' },
  { complianceId: 'EVT-28', type: 'event', act: 'MMDR 1957', title: 'Revised Mining Lease execution', detail: 'Pay NPV/lease-transfer charges to CAMPA.', dept: 'Legal/Mining', recurrence: 'Event-based', dueDate: 'At lease execution', alertDate: 'On trigger', authority: 'State Govt; CAMPA', penalty: 'Lease determination' },
  { complianceId: 'EVT-29', type: 'event', act: 'Van Adhiniyam 1980', title: 'UG Forest Permission granted compliance', detail: 'On grant — comply with FC stipulations.', dept: 'Environment/Forest', recurrence: 'Event-based', dueDate: 'Per sanction milestones', alertDate: 'On grant', authority: 'MoEFCC / Nodal DFO, Raigarh', penalty: 'CAMPA recoveries' },
  { complianceId: 'EVT-30', type: 'event', act: 'Draft OSH Regs 2026', title: 'Commencement of UNDERGROUND working (future)', detail: 'Activate full UG regime.', dept: 'Mgr/Safety', recurrence: 'Event-based', dueDate: 'Before UG begins', alertDate: 'Ahead of UG start', authority: 'DGMS; Mines Rescue Station', penalty: 'OSH Code s.94/s.103' },
  { complianceId: 'EVT-31', type: 'event', act: 'Explosives Rules 2008', title: 'Surrender/suspension of any licence', detail: 'Follow surrender procedure; settle returns/refunds.', dept: 'Concerned dept.', recurrence: 'Event-based', dueDate: 'Per rule', alertDate: 'On decision', authority: 'PESO/CECB/CGWA', penalty: 'Per respective statute' },
  { complianceId: 'EVT-32', type: 'event', act: 'Draft OSH Regs 2026', title: 'Working approaching surface-water danger zone', detail: 'Advance written notice before working in danger zone.', dept: 'Mining/Survey', recurrence: 'Event-based', dueDate: '14 days notice', alertDate: '14 days before', authority: 'DGMS', penalty: 'OSH Code s.94' },
  { complianceId: 'EVT-33', type: 'event', act: 'EC cond.28', title: 'Heavy-metal rise in groundwater (fly-ash leachate)', detail: 'Stop further fly-ash dumping immediately.', dept: 'Environment', recurrence: 'Event-based', dueDate: 'Immediately on detection', alertDate: 'On trigger', authority: 'CGWB; SPCB; MoEFCC', penalty: 'EP Act penalties' },
  { complianceId: 'EVT-34', type: 'event', act: 'CTO cond. / EP Act 1986', title: 'Discharge of mine water outside lease', detail: 'Maintain zero-discharge; if discharge, treat to standards.', dept: 'Environment', recurrence: 'Event-based', dueDate: 'On occurrence', alertDate: 'On trigger', authority: 'CECB', penalty: 'EP Act + Water Act penalties' },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected');

    await User.deleteMany({});
    await Compliance.deleteMany({});

    const admin = await User.create({
      name: 'JPL Admin',
      email: 'admin@jplmines.com',
      password: 'Admin@123',
      role: 'admin',
      dept: 'Admin'
    });
    console.log('Admin user created:', admin.email);

    await Compliance.insertMany(compliances);
    console.log(`${compliances.length} compliances seeded`);

    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seed();